### ISSUE TITLE
許願池：Post 不要顯示精選圖片

### ISSUE THREAD

**Issue by haway** [terrylinooo/mynote#3]
或許已經有這個功能，如果已經有的話請告知一下。

就是可以設定文章內要不要顯示 "精選圖片"

謝謝。

**Comment by terrylinooo** [comment]
如果有設定 featured image 的話，會出現，這比較大眾偏好的功能，假如您不需要的話。

![image](https://user-images.githubusercontent.com/11989371/53396657-f7d60780-39df-11e9-9c19-e3d30eab66cb.png)

```css
.markdown-body > figure {
	display: none;
}
```

可自行在客製化的 css 裡加入這段代碼。
